= Rationale for the seven base dimensions

diman is based on the seven base dimensions for the quantities; mass,
length, time, electric current, thermodynamic temperature, amount of
substance and luminous intensity. Therefore, one may think of these
seven names as the dimension names. But, they are quantities not
dimensions. So,

== What is a dimension?

This is best defined by McNish as

____
It is simply a tag we attach to a quantity in an equation expressing
some physical law... [D]imensions are only symbols of an elementary
algebra, involving neither addition nor subtraction. To ask what are the
true or natural dimensions of a quantity makes no more sense than to ask
what is the true or natural word for goldfish.
link:#McNish1957[[McNish1957]]
____

=== Dimension vs Quantity Units

Since dimensions are represented by symbols, they follow the rule of
algebra. However, units (eg. meter is a unit for the quanity length) are
not bound by the rules of an algebra. This is an important concept for
dimensional analysis.

Due to this reason we can have a minimum number of dimension to create a
dimensional system such that we can relate arbitrarily chosen chosen
into one coherent system. But, limiting the units to certain "absolute"
units from which other units are derived would be problem specific.

If one could just assign a magnitude to a single quantity and consider
this as the "absolute" unit we might be able to derive a system of units
(consisten around this absolute unit) to measure all other quantities by
arbitrarily assigning values to several physical constants. But, in
practice measuring the units for many of the quantities in this system
will require difficult experiments that cannot be performed accurately.
McNish says,

____
The magnitudes of quantities are not determined by nature, but by the
units we have arbitrarily chosen for our measurement system.
link:#McNish1957[[McNish1957]]
____

== Why seven elemental dimensions is a good start?

McNish's argument for it is

____
{empty}[F]or the simplest mechanical quantities we need four dimensions
to avoid ambiguities, five, if we include solid angle; that if we set
one of these quantities equal to unity we can get along with four. But
having one quantity equal to unity we cannot set another equal to unity
without creating an ambiguity. Thus, unity itself becomes like a
dimension, so again we may say we have five. Heat and electromagnetism
add at least two more required dimensions. So I might venture to say
that we should have seven elemental dimensions, at least, but I do not
know, because I do not comprehend all of physics. One, of course, may
get along with fewer dimensions if he will tolerate some ambiguities.
link:#McNish1957[[McNish1957]]
____

== The seven base dimensions for diman

[width="70%",cols="55%,45%",options="header",]
|===
|Quantity |Dimension (Notation)
|mass |[M]
|length |[L]
|time |[T]
|electric current |[A]
|thermodynamic temperature |[K]
|amount of substance |[mol]
|luminous intensity |[cd]
|===

The seven base dimensions for diman is based on the International System
of Units, SI units link:#BIPM2020[[BIPM2020]].

____
A part of the secret of analysis is the art of using notation well. -
Leibniz
____

This is implemented in diman as

....
=> (pprint base_dimensions)
[{:quantity "mass", :dimension "[M]"}
{:quantity "length", :dimension "[L]"}
{:quantity "time", :dimension "[T]"}
{:quantity "electric current", :dimension "[A]"}
{:quantity "thermodynamic temperature", :dimension "[K]"}
{:quantity "luminous intensity", :dimension "[cd]"}
{:quantity "amount of substance", :dimension "[mol]"}]
....

=== Derived Dimensions

Some well known dimensions derived from the `base_dimensions` are placed
in the `standard_formula`.

....
=> (pprint standard_formula)
[{:quantity "volume", :dimension "[L^(3)]"}
{:quantity "frequency", :dimension "[T^(-1)]"}
{:quantity "velocity", :dimension "[L^(1)*T^(-1)]"}
{:quantity "acceleration", :dimension "[L^(1)*T^(-2)]"}
{:quantity "force", :dimension "[M^(1)*L^(1)*T^(-2)]"}
{:quantity "mass density", :dimension "[M^(1)*L^(-3)]"}
{:quantity "energy", :dimension "[M^(1)*L^(2)*T^(-2)]"}
{:quantity "work", :dimension "[M^(1)*L^(2)*T^(-2)]"}
{:quantity "amount of heat", :dimension "[M^(1)*L^(2)*T^(-2)]"}
{:quantity "pressure", :dimension "[M^(1)*L^(-1)*T^(-2)]"}
{:quantity "stress", :dimension "[M^(1)*L^(-1)*T^(-2)]"}
{:quantity "catalytic activity", :dimension "[mol^(1)*T^(-1)]"}
{:quantity "charge", :dimension "[A^(1)*T^(1)]"}
{:quantity "capacitance", :dimension "[M^(-1)*L^(-2)*T^(4)*A^(2)]"}
{:quantity "inductance", :dimension "[M^(1)*L^(2)*T^(-2)*A^(-2)]"}
{:quantity "resistance", :dimension "[M^(1)*L^(2)*T^(-3)*A^(-2)]"}
{:quantity "conductance", :dimension "[M^(-1)*L^(-2)*T^(3)*A^(2)]"}
{:quantity "magnetic flux density", :dimension "[M^(1)*T^(-2)*A^(-1)]"}
{:quantity "electromotive force", :dimension "[M^(1)*L^(2)*T^(-3)*A^(-1)]"}
{:quantity "power", :dimension "[M^(1)*L^(2)*T^(-3)]"}
{:quantity "magnetic flux", :dimension "[M^(1)*L^(2)*T^(-2)*A^(-1)]"}]
....

Notice that the derived dimensions are in a sense the _dimensional
formula for respective quantity_. Hence, the name `standard_formula`.

== References

[[citations]]
[#BIPM2020 .citation-label]#BIPM2020#::
  BIPM (2020). _Base unit definitions_. Retrieved from the
  https://www.bipm.org/en/measurement-units/base-units.html[Base units
  page].
[#McNish1957 .citation-label]#McNish1957#::
  McNish, A. G. (1957, April 1). Dimensions units and standards.
  _Physics Today_, 10(4), 19.
  https://doi.org/10.1063/1.3060330[10.1063/1.3060330]
